
import type { Metadata } from "next";
import "./globals.css";
import Nav from "@/components/Nav/nav";



export const metadata: Metadata = {
  title: "PERSONAL PORTFOLIO,",
  description: "Generated by Faiza Naaz",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html >
      <body>
        <Nav/>
        {children}
      </body>
    </html>
  );
}
